name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7  # Flutter animations package
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.1.0
  file_picker: ^9.2.1
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/loading.json  # This should be under assets
    - assets/animation 3.json 
    - assets/animation 2.json
    - assets/animation 1.json
    - assets/animation 4.json
   
    
